# Generated by Django 3.2.12 on 2022-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor",
                    models.CharField(max_length=255, verbose_name="Doctor Name"),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnosis")),
                ("notes", models.TextField(verbose_name="Doctor Notes")),
            ],
        ),
        migrations.CreateModel(
            name="MedicinePrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine",
                    models.CharField(max_length=255, verbose_name="Medicine Name"),
                ),
                (
                    "doses",
                    models.CharField(blank=True, max_length=255, verbose_name="Doses"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_name",
                    models.CharField(max_length=255, verbose_name="Test Name"),
                ),
                ("test_result", models.TextField(verbose_name="Test Result")),
            ],
        ),
    ]
