# Generated by Django 3.2.12 on 2022-02-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinerecord',
            name='prescription',
        ),
        migrations.CreateModel(
            name='PrescriptionForPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecord.medicineprescription')),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientrecord.medicinerecord')),
            ],
        ),
    ]
