# Generated by Django 3.2.12 on 2022-02-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patientrecord", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.patient"
            ),
        ),
        migrations.AddField(
            model_name="medicinerecord",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.patient"
            ),
        ),
        migrations.AddField(
            model_name="medicinerecord",
            name="prescriptions",
            field=models.ManyToManyField(to="patientrecord.MedicinePrescription"),
        ),
        migrations.AddField(
            model_name="doctornotes",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.patient"
            ),
        ),
    ]
