# Generated by Django 3.2.12 on 2022-02-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('patientrecord', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinerecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patient'),
        ),
    ]
