# Generated by Django 3.2.12 on 2022-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecord', '0002_auto_20220211_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerecord',
            name='prescriptions',
            field=models.ManyToManyField(to='patientrecord.MedicinePrescription'),
        ),
    ]
