# Generated by Django 3.2.12 on 2022-02-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opd", "0001_initial"),
        ("patientrecord", "0003_alter_medicinerecord_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctornotes",
            name="doctor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="opd.doctor"
            ),
        ),
    ]
