# Generated by Django 3.2.12 on 2022-02-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_referredpatients"),
        ("opd", "0001_initial"),
        ("patientrecord", "0004_alter_doctornotes_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctornotes",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="opd.doctor"
            ),
        ),
        migrations.AlterField(
            model_name="doctornotes",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.patient"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.patient"
            ),
        ),
    ]
