# Generated by Django 3.2.12 on 2022-02-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('patientrecord', '0004_delete_prescriptionforpatients'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Test Name')),
                ('test_result', models.TextField(verbose_name='Test Result')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=255, verbose_name='Doctor Name')),
                ('diagnosis', models.TextField(max_length=255, verbose_name='Diagnosis')),
                ('notes', models.TextField(verbose_name='Doctor Notes')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.patient')),
            ],
        ),
    ]
