# Generated by Django 3.2.12 on 2022-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientrecord", "0005_auto_20220212_1004"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="media",
            field=models.TextField(default=""),
        ),
    ]
