# Generated by Django 3.2.12 on 2022-02-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecord', '0005_doctornotes_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotes',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
    ]
