# Generated by Django 3.2.12 on 2022-02-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientrecord", "0007_auto_20220212_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctornotes",
            name="predicted_disease",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Predicted Disease"
            ),
        ),
    ]
