# Generated by Django 3.2.12 on 2022-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecord', '0008_doctornotes_predicted_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotes',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='doctornotes',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Doctor Notes'),
        ),
    ]
