# Generated by Django 3.2.12 on 2022-02-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientrecord', '0009_auto_20220213_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='media',
            field=models.TextField(blank=True, default=''),
        ),
    ]
