# Generated by Django 3.2.12 on 2022-02-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Disease Name')),
                ('link', models.TextField(verbose_name='More info Link')),
                ('symptoms', models.TextField(verbose_name='Symptoms')),
                ('causes', models.TextField(verbose_name='Causes')),
                ('risk_factor', models.TextField(verbose_name='Risk Factor')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('treatment', models.TextField(verbose_name='Treatment')),
                ('medication', models.TextField(verbose_name='Medication')),
                ('prevention', models.TextField(verbose_name='Prevention')),
            ],
        ),
    ]
