# Generated by Django 3.2.12 on 2022-02-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
