# Generated by Django 3.2.12 on 2022-02-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(verbose_name='Hospital Latitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(verbose_name='Hospital Longitude'),
        ),
    ]
