# Generated by Django 3.2.12 on 2022-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220211_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhar',
            field=models.CharField(blank=True, max_length=20, verbose_name='Patient Aadhar Number'),
        ),
    ]
